pipeline {
    agent any
    stages {
        stage('Build') {
            when {
                changeset "**/client/**"
            }
            steps {
                dir('client') {
                    // Build steps for AuthService
                    sh 'docker build -t emash90/skin_client .'
                }
            }
        }
    }
}
