version: '3.1'
services:
  db:
    image: mongo
    container_name: mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    env_file:
      - .env
    volumes:
      - mongodb:/data/db


volumes:
  mongodb: