version: '3.1'
services:
  db:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_USERNAME=emash90
      - MONGO_PASSWORD=123456
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DB=auth
  authService:
    build: ./authservice
    image: authservicecontainer
    ports:
      - "4000:4000"
    volumes:
      - ./authservice:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGO_USERNAME=emash90
      - MONGO_PASSWORD=123456
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DB=auth
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
    command: ["npm", "run", "dev"]
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379