version: '3.1'
services:
  db:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
       - mongodb:/data/db
    environment:
      - MONGO_USERNAME=emash90
      - MONGO_PASSWORD=123456
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DB=auth
  authService:
    build: ./backend/authservice
    image: authservicecontainer
    ports:
      - "4000:4000"
    volumes:
      - ./backend/authservice:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGO_USERNAME=emash90
      - MONGO_PASSWORD=123456
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DB=auth
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
    command: ["npm", "run", "dev"]
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  apiGateway:
    build: ./backend/api-gateway
    image: apigatewaycontainer
    ports:
      - "5000:5000"
    volumes:
      - ./backend/api-gateway:/app
      - /app/node_modules
    depends_on:
      - authService
      - productService
    environment:
      - AUTH_SERVICE_HOST=authService
      - PRODUCT_SERVICE_HOST=productService
      - ORDER_SERVICE_HOST=orderService
    command: ["npm", "run", "dev"]
  productService:
    build: ./backend/productService
    image: productservicecontainer
    ports:
      - "5001:5001"
    volumes:
      - ./backend/productservice:/app
      - /app/node_modules
    depends_on:
      - db
      - redis
    environment:
      - NODE_ENV=development
      - MONGO_USERNAME=emash90
      - MONGO_PASSWORD=123456
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DB=product
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["npm", "run", "dev"]
  orderService:
    build: ./backend/orderService
    image: orderservicecontainer
    ports:
      - "5002:5002"
    volumes:
      - ./backend/orderservice:/app
      - /app/node_modules
    depends_on:
      - db
      - redis
    environment:
      - NODE_ENV=development
      - MONGO_USERNAME=emash90
      - MONGO_PASSWORD=123456
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DB=order
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["npm", "run", "dev"]
  client:
    build: ./client
    image: clientcontainer
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_GATEWAY_HOST=apiGateway
      - REACT_APP_API_GATEWAY_PORT=5000
    command: ["npm", "start"]

volumes:
  mongodb: