version: '3.1'
services:
  db:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
       - mongodb:/data/db
    environment:
      - MONGO_USERNAME=emash90
      - MONGO_PASSWORD=123456
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DB=auth
  authService:
    image: emash90/skin-backend-auth:1.0.1
    container_name: authService
    volumes:
      - ./backend/AuthService:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGO_USERNAME=emash90
      - MONGO_PASSWORD=123456
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DB=auth
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
    command: ["npm", "run", "dev"]
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  apiGateway:
    image: emash90/skin-backend-gateway:1.0.1
    container_name: apiGateway
    ports:
      - "5000:5000"
    volumes:
      - ./backend/API-gateway:/app
      - /app/node_modules
    depends_on:
      - authService
      - productService
    environment:
      - AUTH_SERVICE_HOST=authService
      - AUTH_SERVICE_PORT=4000
      - PRODUCT_SERVICE_HOST=productService
      - PRODUCT_SERVICE_PORT=5001
      - ORDER_SERVICE_HOST=orderService
      - ORDER_SERVICE_PORT=5002
    command: ["npm", "run", "dev"]
  productService:
    image: emash90/skin-backend-products:1.0.1
    container_name: productService
    volumes:
      - ./backend/productService:/app
      - /app/node_modules
    depends_on:
      - db
      - redis
    environment:
      - NODE_ENV=development
      - MONGO_USERNAME=emash90
      - MONGO_PASSWORD=123456
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DB=product
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=5001
    command: ["npm", "run", "dev"]
  orderService:
    image: emash90/skin-backend-orders:1.0.1
    container_name: orderService
    volumes:
      - ./backend/orderService:/app
      - /app/node_modules
    depends_on:
      - db
      - redis
    environment:
      - NODE_ENV=development
      - MONGO_USERNAME=emash90
      - MONGO_PASSWORD=123456
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DB=order
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=5002
    command: ["npm", "run", "dev"]
  client:
    image: emash90/skin_client:1.0.1
    container_name: client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./client/.env
    command: ["npm", "start"]

volumes:
  mongodb: