version: '3.7'

services:
  authService:
    image: emash90/skin-backend-auth:1.0.2
    environment:
      NODE_ENV_FILE: /run/secrets/NODE_ENV
      REDIS_HOST_FILE: /run/secrets/REDIS_HOST
      REDIS_PORT_FILE: /run/secrets/REDIS_PORT
      AUTH_SERVICE_PORT_FILE: /run/secrets/AUTH_SERVICE_PORT
    secrets:
      - NODE_ENV
      - REDIS_HOST
      - REDIS_PORT
      - AUTH_SERVICE_PORT
    ports:
      - "4001:4001"
    command: ["npm", "run", "dev"]

  redis:
    image: redis
    environment:
      REDIS_HOST_FILE: /run/secrets/REDIS_HOST
      REDIS_PORT_FILE: /run/secrets/REDIS_PORT
    ports:
      - "6379:6379"
    secrets:
      - REDIS_HOST
      - REDIS_PORT

  apiGateway:
    image: emash90/skin-backend-gateway:1.0.2
    environment:
      NODE_ENV_FILE: /run/secrets/NODE_ENV
      REDIS_HOST_FILE: /run/secrets/REDIS_HOST
      REDIS_PORT_FILE: /run/secrets/REDIS_PORT
      AUTH_SERVICE_PORT_FILE: /run/secrets/AUTH_SERVICE_PORT
      PRODUCT_SERVICE_PORT_FILE: /run/secrets/PRODUCT_SERVICE_PORT
      ORDER_SERVICE_PORT_FILE: /run/secrets/ORDER_SERVICE_PORT
      API_GATEWAY_PORT_FILE: /run/secrets/API_GATEWAY_PORT
      CLIENT_PORT_FILE: /run/secrets/CLIENT_PORT
    secrets:
      - NODE_ENV
      - REDIS_HOST
      - REDIS_PORT
      - AUTH_SERVICE_PORT
      - PRODUCT_SERVICE_PORT
      - ORDER_SERVICE_PORT
      - API_GATEWAY_PORT
      - CLIENT_PORT
    ports:
      - "4000:4000"
    command: ["npm", "run", "dev"]

  productService:
    image: emash90/skin-backend-products:1.0.2
    environment:
      NODE_ENV_FILE: /run/secrets/NODE_ENV
      REDIS_HOST_FILE: /run/secrets/REDIS_HOST
      REDIS_PORT_FILE: /run/secrets/REDIS_PORT
      AUTH_SERVICE_PORT_FILE: /run/secrets/AUTH_SERVICE_PORT
      PRODUCT_SERVICE_PORT_FILE: /run/secrets/PRODUCT_SERVICE_PORT
      API_GATEWAY_PORT_FILE: /run/secrets/API_GATEWAY_PORT
      CLIENT_PORT_FILE: /run/secrets/CLIENT_PORT
    secrets:
      - NODE_ENV
      - REDIS_HOST
      - REDIS_PORT
      - AUTH_SERVICE_PORT
      - PRODUCT_SERVICE_PORT
      - API_GATEWAY_PORT
      - CLIENT_PORT
    ports:
      - "4002:4002"
    command: ["npm", "run", "dev"]

  orderService:
    image: emash90/skin-backend-orders:1.0.2
    environment:
      NODE_ENV_FILE: /run/secrets/NODE_ENV
      REDIS_HOST_FILE: /run/secrets/REDIS_HOST
      REDIS_PORT_FILE: /run/secrets/REDIS_PORT
      AUTH_SERVICE_PORT_FILE: /run/secrets/AUTH_SERVICE_PORT
      ORDER_SERVICE_PORT_FILE: /run/secrets/ORDER_SERVICE_PORT
      PRODUCT_SERVICE_PORT_FILE: /run/secrets/PRODUCT_SERVICE_PORT
      API_GATEWAY_PORT_FILE: /run/secrets/API_GATEWAY_PORT
      CLIENT_PORT_FILE: /run/secrets/CLIENT_PORT
    secrets:
      - NODE_ENV
      - REDIS_HOST
      - REDIS_PORT
      - AUTH_SERVICE_PORT
      - ORDER_SERVICE_PORT
      - PRODUCT_SERVICE_PORT
      - API_GATEWAY_PORT
      - CLIENT_PORT
    ports:
      - "4003:4003"
    command: ["npm", "run", "dev"]

  client:
    image: emash90/skin_client:1.0.2
    environment:
      NODE_ENV_FILE: /run/secrets/NODE_ENV
      REACT_APP_CLOUDINARY_CLOUD_NAME_FILE: /run/secrets/REACT_APP_CLOUDINARY_CLOUD_NAME
      REACT_APP_CLOUDINARY_UPLOAD_PRESET_FILE: /run/secrets/REACT_APP_CLOUDINARY_UPLOAD_PRESET
      REACT_APP_API_GATEWAY_HOST_FILE: /run/secrets/REACT_APP_API_GATEWAY_HOST
      CLIENT_PORT_FILE: /run/secrets/CLIENT_PORT
    secrets:
      - NODE_ENV
      - REACT_APP_CLOUDINARY_CLOUD_NAME
      - REACT_APP_CLOUDINARY_UPLOAD_PRESET
      - REACT_APP_API_GATEWAY_HOST
      - CLIENT_PORT
      - API_GATEWAY_PORT
    ports:
      - "3000:3000"
    command: ["npm", "start"]

secrets:
  NODE_ENV:
    external: true
  REDIS_HOST:
    external: true
  REDIS_PORT:
    external: true
  AUTH_SERVICE_PORT:
    external: true
  PRODUCT_SERVICE_PORT:
    external: true
  ORDER_SERVICE_PORT:
    external: true
  API_GATEWAY_PORT:
    external: true
  CLIENT_PORT:
    external: true
  REACT_APP_CLOUDINARY_CLOUD_NAME:
    external: true
  REACT_APP_CLOUDINARY_UPLOAD_PRESET:
    external: true
  REACT_APP_API_GATEWAY_HOST:
    external: true
    