pipeline {
    agent any
    stages {
        stage('Build') {
            when {
                changeset "**/backend/productService/**"
            }
            steps {
                dir('backend/API-gateway') {
                    // Build steps for AuthService
                    sh 'docker build -t emash90/skin-backend-products .'
                }
            }
        }
    }
}
